### PR TITLE
Proper Android backstack handling

### PR DESCRIPTION
**Pull request by jaapmengers**
Current backstack behaviour on Android leads to the app closing rather than hiding the form. I reproduced the behaviour in the bundled UsabillaSampleApp in this repo. See:

usabilla

### CODE REVIEW

**Comment by LouiseBC** [comment]
Could someone review this please? I need this fix too 🙃

**Comment by torkvell** [comment]
Hi @jaapmengers & @LouiseBC,

Thank you for your feedback. 

This is an expected behavior, given that you are clicking on the phone navigation and not on the form navigation. 

Usabilla shows the form and handles the touches it receives on its navigation buttons (the ones on the bottom of the form to dismiss or submit)

If you click on the back button of the phone (as the video shows) that is an action that falls under the responsibilities of the app developer to intercept and handle.

I hope this clarifies, please let me know if there is anything else we can assist on.

**Comment by Frank1234** [comment]
Usabilla opens the form, so they should handle closing it too. Usabilla replaces the current fragment without adding the tranformation to the backstack so that it can be undone. If they would add it to the backstack, as done in this PR, regular android behaviour on any back button or gesture would undo the transformation, instead of closing the app.

**Comment by jaapmengers** [comment]
@torkvell Thanks for your response. The default behaviour for the back button on Android is to move back in the backstack maintained by the application. Per the [Android guidlines](https://developer.android.com/guide/navigation/navigation-custom-back):

>Back navigation is how users move backward through the history of screens they previously visited. All Android devices provide a Back button for this type of navigation, so you should not add a Back button to your app’s UI. Depending on the user’s Android device, this button might be a physical button or a software button.
>
>Android maintains a back stack of destinations as the user navigates throughout your application. This usually allows Android to properly navigate to previous destinations when the Back button is pressed.

In this case, the usabilla-u4a-react-native code governs the behaviour of the back button in the `UsabillaBridge.java` file. The code explicitly removes and replaces our app's fragment with Usabilla's form fragment. We're most likely unable to intervene from our React Native code in a sensible way, since our fragment is removed.

Thinking in terms of [Navigation Graphs](https://developer.android.com/guide/navigation/navigation-design-graph), I'd argue that the Usabilla form should be thought of as a nested graph that is pushed to the backstack, as is done in this PR. Regular Android behaviour on any back button or back gesture would remove the Usabilla fragment, thus showing the last app fragment that was shown by the app.

As it stands, we are forced to maintain a fork of your library in which we correct this behaviour. Since this introduces considerable maintenance effort, we would very much appreciate a fix on your end. 

Can you elaborate on the reasoning behind replacing the fragment, rather than pushing it on the backstack? Thanks

**Comment by jaapmengers** [comment]
@torkvell Do you happen to have some time to look at my question? This remains an issue for us.

**Pull request closed without merging**
